#!/usr/bin/env bash
# 103_clerk-env.sh — Interactive Clerk publishable-key setup for tagkin-desktop (D1).
# Writes .env (CLERK_PUBLISHABLE_KEY + TAGKIN_API_URL). NEVER commits secrets (R8).
# Only the publishable key belongs in the desktop client — never CLERK_SECRET_KEY.
set -euo pipefail
MAC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=_env.sh
source "${MAC_DIR}/_env.sh"

ENV_FILE="${TAGKIN_DESKTOP_ROOT}/.env"
EXAMPLE="${TAGKIN_DESKTOP_ROOT}/.env.example"

if [[ ! -f "${ENV_FILE}" ]]; then
  cp "${EXAMPLE}" "${ENV_FILE}"
  chmod 600 "${ENV_FILE}"
  echo "created .env from .env.example"
fi

CURRENT_PUB=""
CURRENT_API="http://localhost:8787"
while IFS= read -r line || [[ -n "${line}" ]]; do
  [[ -z "${line}" || "${line}" == \#* ]] && continue
  key="${line%%=*}"
  val="${line#*=}"
  val="${val%\"}"
  val="${val#\"}"
  case "${key}" in
    CLERK_PUBLISHABLE_KEY) CURRENT_PUB="${val}" ;;
    TAGKIN_API_URL) CURRENT_API="${val}" ;;
  esac
done < "${ENV_FILE}"

echo ""
echo "==> Clerk Dashboard (desktop client)"
echo "    1. https://dashboard.clerk.com -> same application as tagkin-api/web"
echo "    2. API Keys -> copy Publishable key (pk_test_… / pk_live_…)"
echo "    3. Do NOT paste Secret key here (R8 — desktop never holds sk_*)"
echo "    4. Ensure API CLERK_AUTHORIZED_PARTIES allows this Clerk application's JWT azp"
echo "       (web: http://localhost:3000; desktop: https://<instance>.clerk.accounts.dev)"
echo ""

read_line() {
  local prompt="$1"
  local current="$2"
  local value=""
  if [[ -n "${current}" ]]; then
    printf "%s [%s — Enter to keep]: " "${prompt}" "${current}" >&2
  else
    printf "%s: " "${prompt}" >&2
  fi
  IFS= read -r value || true
  if [[ -z "${value}" && -n "${current}" ]]; then
    printf "%s" "${current}"
  else
    printf "%s" "${value}"
  fi
}

PUBLISHABLE="$(read_line "CLERK_PUBLISHABLE_KEY (pk_…)" "${CURRENT_PUB}")"
API_URL="$(read_line "TAGKIN_API_URL" "${CURRENT_API}")"

if [[ -z "${PUBLISHABLE}" ]]; then
  echo "error: CLERK_PUBLISHABLE_KEY is required" >&2
  exit 1
fi
if [[ "${PUBLISHABLE}" == sk_* ]]; then
  echo "error: that looks like a secret key (sk_*). Desktop must only store pk_* (R8)." >&2
  exit 1
fi

{
  echo "# Generated by mac/103_clerk-env.sh — do not commit (R8)."
  echo "CLERK_PUBLISHABLE_KEY=${PUBLISHABLE}"
  echo "TAGKIN_API_URL=${API_URL}"
} > "${ENV_FILE}"
chmod 600 "${ENV_FILE}"

echo ""
echo "==> Clerk desktop env ready (${ENV_FILE}, mode 600)."
echo "    Next (from TagKin-Desktop/mac/):"
echo "      ./11_dev.sh          # run the app (sign-in UI)"
echo "      ./107_test_d1.sh     # D1 regression (mocked; no live Clerk required)"
