# 103_clerk-env.ps1 — Interactive Clerk publishable-key setup for tagkin-desktop (D1).
# Writes .env (CLERK_PUBLISHABLE_KEY + TAGKIN_API_URL). NEVER commits secrets (R8).
$ErrorActionPreference = 'Stop'
$winDir = Split-Path -Parent $PSCommandPath
. (Join-Path $winDir '_env.ps1')

$envFile = Join-Path $global:TagKinDesktopRoot '.env'
$example = Join-Path $global:TagKinDesktopRoot '.env.example'

if (-not (Test-Path $envFile)) {
  Copy-Item $example $envFile
  Write-Host 'created .env from .env.example'
}

$currentPub = ''
$currentApi = 'http://localhost:8787'
Get-Content $envFile | ForEach-Object {
  $line = $_.Trim()
  if (-not $line -or $line.StartsWith('#')) { return }
  $eq = $line.IndexOf('=')
  if ($eq -le 0) { return }
  $key = $line.Substring(0, $eq).Trim()
  $val = $line.Substring($eq + 1).Trim().Trim('"').Trim("'")
  switch ($key) {
    'CLERK_PUBLISHABLE_KEY' { $currentPub = $val }
    'TAGKIN_API_URL' { $currentApi = $val }
  }
}

Write-Host ''
Write-Host '==> Clerk Dashboard (desktop client)'
Write-Host '    1. https://dashboard.clerk.com -> same application as tagkin-api/web'
Write-Host '    2. API Keys -> copy Publishable key (pk_test_… / pk_live_…)'
Write-Host '    3. Do NOT paste Secret key here (R8 — desktop never holds sk_*)'
Write-Host ''

function Read-LineKeep([string]$Prompt, [string]$Current) {
  if ($Current) {
    $input = Read-Host "$Prompt [$Current — Enter to keep]"
  } else {
    $input = Read-Host $Prompt
  }
  if (-not $input -and $Current) { return $Current }
  return $input
}

$publishable = Read-LineKeep 'CLERK_PUBLISHABLE_KEY (pk_…)' $currentPub
$apiUrl = Read-LineKeep 'TAGKIN_API_URL' $currentApi

if (-not $publishable) {
  Write-Error 'CLERK_PUBLISHABLE_KEY is required'
}
if ($publishable -like 'sk_*') {
  Write-Error 'that looks like a secret key (sk_*). Desktop must only store pk_* (R8).'
}

@"
# Generated by win/103_clerk-env.ps1 — do not commit (R8).
CLERK_PUBLISHABLE_KEY=$publishable
TAGKIN_API_URL=$apiUrl
"@ | Set-Content -Path $envFile -Encoding utf8

Write-Host ''
Write-Host "==> Clerk desktop env ready ($envFile)."
Write-Host '    Next (from TagKin-Desktop\win\):'
Write-Host '      ./11_dev.ps1'
Write-Host '      ./107_test_d1.ps1'
